theme: jekyll-theme-hacker
title: Thomas Rückert
url: "https://thomasrueckert.github.io"

author:
  name: 'Thomas Rückert'
  github_username:  ThomasRueckert
  email: thomas.rueckert@s2010.tu-chemnitz.de
